### ISSUE TITLE
SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS

### ISSUE THREAD

**Issue by Rstacx** [kuumoneko/GoogleBard-js#2]
After a while this will come to the response

**Comment by kuumoneko** [comment]
can you show full response?

**Comment by Rstacx** [comment]
The full response comes from SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS

**Comment by kuumoneko** [comment]
> The full response comes from SWML_DESCRIPTION_FROM_YOUR_INTERNET_ADDRESS

Nah.... I can't find this error... API will be tired before I found that error. 😅😅😅
